#  vim ft=yaml:expandtab:sw=2:ts=2
---
language:
  - c
  - python

compiler:
  - clang
  - gcc

install:
  - sudo apt update
  - sudo apt install libvorbis-dev libflac-dev libsndfile1-dev

script:
  - "cd accuraterip && make"
