#!/bin/sh
file=test/short.wav
accuraterip-checksum --accuraterip-v1 $file 3 5
accuraterip-checksum --accuraterip-v1 $file 1 5
accuraterip-checksum --accuraterip-v1 $file 5 5
accuraterip-checksum --accuraterip-v1 $file 1 1

echo "\n====\n\n";

accuraterip-checksum --accuraterip-v2 $file 3 5
accuraterip-checksum --accuraterip-v2 $file 1 5
accuraterip-checksum --accuraterip-v2 $file 5 5
accuraterip-checksum --accuraterip-v2 $file 1 1
